site:
  title: SKaiNET Documentation
  start_page: skainet::index.adoc
  keys:
    google_analytics: ''
content:
  sources:
    - url: ../
      branches: HEAD
      start_path: docs/src/docs
      edit_url: 'https://github.com/sk-ai-net/skainet-doc/{path}'


ui:
  # Use the stock Antora Default UI as baseline (left nav, toolbar, breadcrumbs).
  # You can pin a version instead of "latest" if you prefer
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: ./ui-supplemental

runtime:
  cache_dir: ./.cache/antora

asciidoc:
  attributes:
    page-pagination: ''
    stem: ''
    icons: font
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    table-caption: false
    example-caption: false
    listing-caption: false
    hide-uri-scheme: '@'
    kroki-server-url: https://kroki.vshn.net/
    kroki-fetch-diagram: ''
    plantuml-server-url: 'https://www.plantuml.com/plantuml'
  # extensions:
    # - asciidoctor-kroki
    # - asciidoctor-plantuml

output:
  destinations:
    - provider: fs
      path: ./_public
      clean: true

